### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by apasel422** [contain-rs/linked-list#1]
1. [Set Travis's `GH_TOKEN` environment variable](https://travis-ci.org/contain-rs/linked-list/settings/env_vars/new) after [creating a new personal access token](https://github.com/settings/tokens/new). You only need to give it the `public_repo` permission.
2. Create an empty `gh-pages` branch:

    ```sh
    git checkout --orphan gh-pages
    git rm -rf '*'
    git commit --allow-empty -m 'create `gh-pages` branch'
    git push origin gh-pages
    ```
3. Restart [the first build](https://travis-ci.org/contain-rs/linked-list/builds/54894616).

@Gankro

**Comment by Gankro** [comment]
Aha, I was hoping this could be more magic

**Comment by Gankro** [comment]
Looks like I might need a GH_BRANCH variable too?

**Comment by Gankro** [comment]
Ah no that's built in. Not sure what else is left to do?

**Comment by apasel422** [comment]
Hmm, it's saying that authentication failed. Let me investigate.

**Comment by apasel422** [comment]
Did you set the value of the `GH_TOKEN` variable to whatever your newly created personal access token was?

**Comment by apasel422** [comment]
(i.e. copy and paste the token itself into the value field on Travis CI)

**Comment by Gankro** [comment]
Looks like I made a copy-paste error. Github says the token was never used.

**Comment by Gankro** [comment]
Worked.
